name: Release Workflow

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git author information
        run: |
          git config --global user.email "f.lajszczak@gmail.com"
          git config --global user.name "Franciszek Łajszczak"


      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9 # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version
      
      

      - name: Bump version
        run: bumpversion patch --verbose --commit# Adjust as needed

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version
